[project]
name = 'clarity'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-deposit'
[contracts.fundraising]
path = 'contracts/fundraising.clar'
clarity_version = 3
epoch = 3.0

#[contracts.governance]
#path = 'contracts/governance.clar'
#clarity_version = 3
#epoch = 3.0

#[contracts.treasury]
#path = 'contracts/treasury.clar'
#clarity_version = 3
#epoch = 3.0

[contracts.policy-registry]
path = 'contracts/policy-registry.clar'
clarity_version = 3
epoch = 3.0

[contracts.liquidity-pool-vault]
path = 'contracts/liquidity-pool-vault.clar'
clarity_version = 3
epoch = 3.0

#[contracts.parameter]
#path = 'contracts/parameter.clar'
#clarity_version = 3
#epoch = 3.0

[contracts.oracle]
path = 'contracts/oracle.clar'
clarity_version = 3
epoch = 3.0

# REMOVED Parameter contract entries
#[contracts.parameter-oracle-impl]
#path = 'contracts/parameter-oracle-impl.clar'
#clarity_version = 3
#epoch = 3.0
#
#[contracts.parameter-trait]
#path = 'contracts/parameter-trait.clar'
#clarity_version = 3
#epoch = 3.0

#[contracts.liquidity-pool]
#path = 'contracts/liquidity-pool.clar'
#clarity_version = 3

#[contracts.liquidation-engine]
#path = 'contracts/liquidation-engine.clar'
#clarity_version = 3
#epoch = 3.0

#[contracts.insurance-fund]
#path = 'contracts/insurance-fund.clar'
#clarity_version = 3
#epoch = 3.0

#[contracts.incentives]
#path = 'contracts/incentives.clar'
#clarity_version = 3
#epoch = 3.0

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
